---
# tasks file for bridge
- import_tasks: system_packages.yml
- import_tasks: system_config.yml
- import_tasks: tor_packages.yml
- import_tasks: tor_config.yml
- import_tasks: service.yml
- import_tasks: bridge_line.yml
