- name: Update system
  apt:
    name: "*"
    update_cache: yes
    state: latest
  tags:
    - install_system_packages
    - update
    - install_all

- name: Packages installation
  apt:
    name: "{{ system_packages }}"
    update_cache: yes
    state: latest
  tags:
    - install_system_packages
    - install_all

- name: Unattended upgrades config file
  template:
    src: 50unattended-upgrades.j2
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: "root"
    group: "root"
    mode: 0644
  tags:
    - unattended_upgrades
    - install_all

- name: Auto upgrades config file
  template:
    src: 20auto-upgrades.j2
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    owner: "root"
    group: "root"
    mode: 0644
  tags:
    - auto_upgrades
    - install_all