- name: Configure Torrc file
  template:
    src: torrc.j2
    dest: "{{ torrc_path }}"
    owner: "root"
    group: "{{ torrc_group }}"
    mode: 0644
  tags:
    - tor_config
    - install_all

- name: Configure net.inet.ip.random_id
  ansible.posix.sysctl:
    name: net.inet.ip.random_id
    value: "1"
    state: present
  when: ansible_os_family == 'FreeBSD'
