# Tor repo
- name: Configuring Tor repository
  template:
    src: tor.list.j2
    dest: "/etc/apt/sources.list.d/tor.list"
    owner: "root"
    group: "root"
    mode: 0644
  tags:
    - tor_repo
    - install_all

- name: Adding Tor Projects key
  ansible.builtin.shell: "wget -O- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --dearmor | tee /usr/share/keyrings/tor-archive-keyring.gpg >/dev/null"
  tags:
    - tor_repo
    - install_all

- name: Update system
  apt:
    name: "*"
    update_cache: yes
    state: latest
  tags:
    - tor_packages
    - install_all

- name: Tor packages installation
  apt:
    name: "{{ tor_packages }}"
    update_cache: yes
    state: latest
  tags:
    - tor_packages
    - install_all
