- name: Configure Torrc file
  template:
    src: torrc.j2
    dest: "{{ torrc_path }}"
    owner: "root"
    group: "{{ torrc_group }}"
    mode: 0644
  tags:
    - tor_config
    - install_all

- name: Configure net.inet.ip.random_id
  ansible.posix.sysctl:
    name: net.inet.ip.random_id
    value: "1"
    state: present
  when: ansible_os_family == 'FreeBSD'

- name: Configure kern.maxfiles
  ansible.posix.sysctl:
    name: kern.maxfiles
    value: 16000
    state: present
  when: ansible_os_family == 'OpenBSD'

- name: Add configuration to login.conf
  blockinfile:
    path: /etc/login.conf
    block: |
      tor:\
        :openfiles-max=13500:\
        :tc=daemon:
  when: ansible_os_family == 'OpenBSD'
